<?php

$lang['PiwigoAI'] = 'Piwigo IA';
$lang['(Generated by Artificial Intelligence)'] = '(Généré par l\'intelligence artificielle)';
$lang['ai_send_picture_file'] = 'Envoyer le fichier image';
$lang['ai_send_picture_file_description'] = 'Envoyer un fichier image au lieu de l’URL de l’image.';
$lang['ai_ticket_callback'] = 'Retour automatique des résultats';
$lang['ai_ticket_callback_description'] = 'Le serveur IA renvoie directement les résultats au lieu d’utiliser un système de consultation périodique.';
$lang['ai_description_prefix'] = 'Préfixe de description';
$lang['ai_description_prefix_description'] = 'Texte ajouté au début des descriptions générées par l’IA.';
$lang['ai_url_server'] = 'URL du serveur IA';
$lang['ai_url_server_description'] = 'URL du serveur IA utilisé pour le traitement.';
$lang['Credits owned'] = 'Crédits disponibles';
$lang['credits left'] = 'crédits restants';
$lang['Unsed credit wont be refund'] = 'Les crédits non utilisés ne seront pas remboursés.';
$lang['Buy credits'] = 'Acheter des crédits';
$lang['ai_api_key'] = 'Clé API';
$lang['ai_api_key_description'] = 'Clé d\'authentification pour le serveur IA.';
$lang['ai_missing_api_key'] = 'Aucune clé API configurée ou la clé est invalide. Veuillez vérifier vos paramètres.';

