<?php

$lang['PiwigoAI'] = 'Piwigo AI';
$lang['(Generated by Artificial Intelligence)'] = '(Generated by Artificial Intelligence)';
$lang['ai_send_picture_file'] = 'Send picture file';
$lang['ai_send_picture_file_description'] = 'Send an image file instead of the image URL.';
$lang['ai_ticket_callback'] = 'Ticket callback';
$lang['ai_ticket_callback_description'] = 'The AI server sends results back directly instead of polling.';
$lang['ai_description_prefix'] = 'Description prefix';
$lang['ai_description_prefix_description'] = 'Text prepended to AI-generated descriptions.';
$lang['ai_url_server'] = 'AI server URL';
$lang['ai_url_server_description'] = 'URL of the AI server used for processing.';
$lang['Credits owned'] = 'Credits owned';
$lang['credits left'] = 'credits left';
$lang['Unsed credit wont be refund'] = 'Unused credits will not be refunded.';
$lang['Buy credits'] = 'Buy credits';
$lang['ai_api_key'] = 'API key';
$lang['ai_api_key_description'] = 'Authentication key for the AI server.';
$lang['ai_missing_api_key'] = 'No API key configured or the key is invalid. Please check your settings.';
