<?php
if (!defined('PHPWG_ROOT_PATH')) die('Hacking attempt!');

include_once(PHPWG_ROOT_PATH.'admin/include/functions.php');

/**
 * `Piwigo AI` : add new pwg method
 */
function p_ai_add_methods($arr)
{
  $service = &$arr[0];

  $service->addMethod(
    'pwg.ai.analyze',
    'p_ws_ai_analyze',
    array(
      'ticket_id' => array(),
      'cost' => array(),
      'ocr' => array('default' => null),
      'description' => array('default' => null),
      'tags' => array('default' => null),
      'embedding' => array('default' => null),
      'process_time' => array(),
    ),
    'Save ticket infos',
    null,
    array(
      'hidden' => false,
      'post_only' => true,
      'admin_only' => false,
    )
  );

  $service->addMethod(
    'pwg.ai.config',
    'p_ws_ai_config',
    array(
      // 'ticket_callback' => array(
      //   'type' => WS_TYPE_BOOL
      // ),
      'ai_url' => array(),
      'description_prefix' => array(
        'flags'=>WS_PARAM_OPTIONAL,
      ),
      'ai_api_key' => array(),
      'pwg_token' => array(),
    ),
    'Change Piwigo AI configuration',
    null,
    array(
      'hidden' => false,
      'post_only' => true,
      'admin_only' => true,
    )
  );

}

/**
 * `WS Piwigo AI` : Endpoint for server ai to callback the result
 */
function p_ws_ai_analyze($params)
{
  global $conf, $logger;

  $query = '
SELECT *
  FROM '.P_AI_TICKETS_TABLE.'
  WHERE ticket_id = "'.pwg_db_real_escape_string($params['ticket_id']).'"  
  ';

  $logger->info('['.__FUNCTION__.'] Saving ' . pwg_db_real_escape_string($params['ticket_id']));

  $result = pwg_db_fetch_assoc(pwg_query($query));
  if (empty($result))
  {
    return new PwgError(WS_ERR_INVALID_PARAM, 'Ticket not found');
  }

  $image = get_image_infos($result['image_id']);

  $ocr = !empty($params['ocr']) ? $params['ocr'] : null;

  $image_update = array('ocr' => $ocr);

  if (!empty($params['description']))
  {
    $prefix = null === $conf[ 'piwigo_ai' ][ 'description_prefix' ]
      ? l10n('(Generated by Artificial Intelligence)')
      : $conf[ 'piwigo_ai' ][ 'description_prefix' ];
    $description = pwg_db_real_escape_string($prefix . ' ' . stripslashes($params['description']));

    if (null !== $image['comment'])
    {
      $description = $image['comment'] . "\n\n" . $description;
    }

    $image_update['comment'] = $description;
  }

  single_update(
    IMAGES_TABLE,
    $image_update,
    array('id' => $result['image_id'])
  );

  if (!empty($params['embedding']))
  {
    $decoded = json_decode($params['embedding'], true);
    if (is_array($decoded))
    {
      pwg_query('
UPDATE `'.IMAGES_TABLE.'`
  SET `embedding` = VEC_FromText(\''.pwg_db_real_escape_string($params['embedding']).'\')
  WHERE id = '.intval($result['image_id']).'
      ');
    }
  }


  if (!empty($params['tags']))
  {
    $tags = explode(',', $params['tags']);
    foreach ($tags as $idx => $tag_candidate)
    {
      $tags[$idx] = pwg_db_real_escape_string(strip_tags(stripslashes(trim($tag_candidate))));
    }

    $tag_list = get_tag_ids($tags);
    set_tags($tag_list, $result['image_id']);

    $query = '
UPDATE `'.TAGS_TABLE.'`
  SET `ai` = \'true\'
  WHERE id IN ('.implode(',', $tag_list).')
';
    pwg_query($query);
  }

  single_update(
    P_AI_TICKETS_TABLE,
    array(
      'cost' => $params['cost'],
      'process_time' => $params['process_time'],
      'status' => 'completed'
    ),
    array('ticket_id' => pwg_db_real_escape_string($params['ticket_id']))
  );

  return 'Ticket updated';  
}

/**
 * `WS Piwigo AI` : Update PiwigoAI configuration
 */
function p_ws_ai_config($params)
{
  global $conf;
  
  if (get_pwg_token() != $params['pwg_token'])
  {
    return new PwgError(403, l10n('Invalid security token'));
  }

  $url_server_ai = rtrim($params['ai_url'], '/');
  $prefix_desc = $params['description_prefix'] ? pwg_db_real_escape_string(strip_tags(stripslashes(trim($params['description_prefix'])))) : null;

  $new_conf = array(
    'api_key' => pwg_db_real_escape_string($params['ai_api_key']),
    'url_server_ai' => pwg_db_real_escape_string($url_server_ai),
    'ticket_callback' => true,
    'description_prefix' => $prefix_desc,
  );
  conf_update_param('piwigo_ai', array_merge($conf['piwigo_ai'], $new_conf), true);
  return 'Configuration saved';
}